version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    container_name: dotnet_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: postgres
      
  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    container_name: dotnet_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
      
    
  dotnet_minio:
    image: minio/minio:latest
    
  dotnet_mongodb:
    image: mongo:latest
    
  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    
  dotnet_main:
    image: dotnet-web
    container_name: dotnet_main
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - dotnet_postgres
      - dotnet_rabbitmq
    environment:
      ConnectionStrings__Default: Server=db;Port=5432;Database=dotnet_postgres;User Id=postgres;Password=postgres
      RabbitMQ__Username: rmuser
      RabbitMQ__Password: rmpassword
      RabbitMQ__Hostname: rabbitmq
      RabbitMQ__Port: 5672
    
  dotnet_mailing:
    image: dotnet-web
    container_name: dotnet_mailing
    environment:
      RabbitMQ__Username: rmuser
      RabbitMQ__Password: rmpassword
      RabbitMQ__Hostname: rabbitmq
      RabbitMQ__Port: 5672
      
      EmailConfig__Email: oris.testmessage1@gmail.com
      EmailConfig__Host: smtp.gmail.com
      EmailConfig__Port: 587
      EmailConfig__Password: lqvoqejdnvbwphcd
    build:
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    ports:
      - "8081:81"
    depends_on:
      - dotnet_rabbitmq
    
  dotnet_storage:
    image: dotnet-web